In [3]:
#variables
x = 10
print(x)
print(type(x))
y = 43.7
print(y)
print(type(y))
z = "Fita"
print(z)
print(type(z))

10
<class 'int'>
43.7
<class 'float'>
Fita
<class 'str'>


In [ ]:
#Python - integer, float, string Adv - List, Tuple, Set, Dicionary
#Numpy, Pandas, matplotlib, poltly

In [6]:
a = int(input())
print(a)
print(type(a))

 9
9
<class 'int'>


In [7]:
#Arithmetic operators (+,-,*,/,%)
a = 10
b = 5.2
print(a-b)
print(a+b)
print(a*b)
print(a/b)
print(a%b)

4.8
15.2
52.0
1.923076923076923
4.8


In [9]:
#Comparison operators(<,<=,>,>=,==,!=)
a = 10
b = 5.2
c = 10
print(a<b)
print(a<=c)
print(a>b)
print(a>=b)
print(a==c)
print(a!=c)

False
True
True
True
True
False


In [11]:
# =, +=, -=, /=, %=
a = 10
a+=10#(a= a+10)
print(a)

20


In [15]:
#membership operator
fita = ["python","java","html","c++"]
if "python" in fita:
    print("yes, it is available")

yes, it is available


In [17]:
#identity operator
a = 10
b = 5
c = 10
print(a is not b)
print(a is c)

True
True


In [19]:
sum = (a + 
      b + 
      c)
print(sum)

25


In [24]:
(2+5)-4*(6/20)#operator precedence

5.8

In [1]:
x=3
print(x)

3


In [3]:
#variables
x=10
print(x)

10


In [5]:
#variables
s=3
print(s)
print(type(s))

3
<class 'int'>


In [6]:
a=3
b=6
c=1
print(a+b)
print(b-c)

9
5


In [10]:
a=int(input())
print(a)
print( type (a))

 2
2
<class 'int'>


In [18]:
fita= ["shalini","rethu","nithish"]
if "shalini" in fita:
       print ("yes,shalini is there")

yes,shalini is there


In [4]:
#Data types - int, float, string, list, tuple, set, dictionary
#string - '', " ", ''' '''
string1 = 'Data Science'
string2 = "Machine Learning"
string3 = '''Deep Learning'''
s1 = 34
print(string1,string2,string3)
print(type(string1))
print(type(s1))

Data Science Machine Learning Deep Learning
<class 'str'>
<class 'int'>


In [6]:
#accessing the string
print(string1[0])
print(string2[5])
print(string3[-2])
print(string1[::-1]) #reverse

D
n
n
ecneicS ataD


In [11]:
#string slicing
print(string1[0:7])
print(string2[4::])
print(string3[3:-2])

Data Sc
ine Learning
p Learni


In [19]:
#updating and deleting
list1 = list(string1) #choice1
list1[3] = 'M'
string4 = ''.join(list1)
print(string4)

string5 = string1[0:3]+'M'+string1[4:] #choice2
print(string5)

string5 = "Changed string"
print(string5)

string6 = string1[0:3]+string1[4:] #delete
print(string6)

DatM Science
DatM Science
Changed string
Dat Science


In [2]:
#List
mylist1 = ["Data Scienc","Machine Learning","Deep Learning"] #preferable
print(type(mylist1))
print(mylist1)
mylist2 = ["python",34,76.1]
print(mylist2)

<class 'list'>
['Data Scienc', 'Machine Learning', 'Deep Learning']
['python', 34, 76.1]


In [24]:
#list access
print(mylist1[1])
print(mylist1[0][6])

Machine Learning
c


In [25]:
mylist3 = list((3,6,9,12))
print(type(mylist3))

<class 'list'>


In [26]:
print(len(mylist1))
print(len(mylist2))
print(len(mylist3))

3
3
4


In [30]:
mylist4 = ["Python","class","morning",[7,8,9,10]]#nested list
print(mylist4[3])
print(mylist4[3][1])
print(len(mylist4))

[7, 8, 9, 10]
8
4


In [6]:
#23 Jan
#Adding the elements
mylist1.append("Networking")
print(mylist1)
mylist1.insert(2,"CCNA")
print(mylist1)
mylist1.extend(["C++","PHP","LAMP"])
print(mylist1)

['Data Scienc', 'Machine Learning', 'CCNA', 'CCNA', 'Deep Learning', 'Networking', 'Networking', 'Networking', 'C++', 'PHP', 'LAMP', 'Networking']
['Data Scienc', 'Machine Learning', 'CCNA', 'CCNA', 'CCNA', 'Deep Learning', 'Networking', 'Networking', 'Networking', 'C++', 'PHP', 'LAMP', 'Networking']
['Data Scienc', 'Machine Learning', 'CCNA', 'CCNA', 'CCNA', 'Deep Learning', 'Networking', 'Networking', 'Networking', 'C++', 'PHP', 'LAMP', 'Networking', 'C++', 'PHP', 'LAMP']


In [7]:
#modify the elements
mylist1[2] = "Andorid"
print(mylist1)

['Data Scienc', 'Machine Learning', 'Andorid', 'CCNA', 'CCNA', 'Deep Learning', 'Networking', 'Networking', 'Networking', 'C++', 'PHP', 'LAMP', 'Networking', 'C++', 'PHP', 'LAMP']


In [8]:
mylist1[7:10] = "Chennai","Bangalore","Kochin","Trichy"
print(mylist1)

['Data Scienc', 'Machine Learning', 'Andorid', 'CCNA', 'CCNA', 'Deep Learning', 'Networking', 'Chennai', 'Bangalore', 'Kochin', 'Trichy', 'PHP', 'LAMP', 'Networking', 'C++', 'PHP', 'LAMP']


In [9]:
#removing list elements
mylist1.remove("CCNA")
print(mylist1)

['Data Scienc', 'Machine Learning', 'Andorid', 'CCNA', 'Deep Learning', 'Networking', 'Chennai', 'Bangalore', 'Kochin', 'Trichy', 'PHP', 'LAMP', 'Networking', 'C++', 'PHP', 'LAMP']


In [11]:
mylist1.pop(3)
print(mylist1)

['Data Scienc', 'Machine Learning', 'Andorid', 'Deep Learning', 'Networking', 'Chennai', 'Bangalore', 'Kochin', 'Trichy', 'PHP', 'LAMP', 'Networking', 'C++', 'PHP']


In [15]:
mylist1.clear()
print(mylist1)
del mylist1

NameError: NameError: name 'mylist1' is not defined

In [16]:
monlist = ['Data Scienc', 'Machine Learning', 'Andorid', 'Deep Learning', 'Networking', 'Chennai', 'Bangalore', 'Kochin', 'Trichy']
print(monlist)

['Data Scienc', 'Machine Learning', 'Andorid', 'Deep Learning', 'Networking', 'Chennai', 'Bangalore', 'Kochin', 'Trichy']


In [17]:
blist = monlist.copy()
print(blist)

['Data Scienc', 'Machine Learning', 'Andorid', 'Deep Learning', 'Networking', 'Chennai', 'Bangalore', 'Kochin', 'Trichy']


In [18]:
blist.sort()
print(blist)

['Andorid', 'Bangalore', 'Chennai', 'Data Scienc', 'Deep Learning', 'Kochin', 'Machine Learning', 'Networking', 'Trichy']


In [19]:
blist.reverse()
print(blist)

['Trichy', 'Networking', 'Machine Learning', 'Kochin', 'Deep Learning', 'Data Scienc', 'Chennai', 'Bangalore', 'Andorid']


In [22]:
#Tuples - Ordered, Unchangealbe, Heterogneous, Can have duplicates
tup1 = (3,5,6,2)
print(type(tup1))
tup2 = ("Vivo","Apple","Nokia")
print(type(tup2))
tup3 = tuple(("Chennai","Trichy","Madurai"))
print(type(tup3))

<class 'tuple'>
<class 'tuple'>
<class 'tuple'>


In [25]:
print(tup1[1])
print(tup2[0])
print(tup3[2])

5
Vivo
Madurai


In [26]:
print(tup1[0:3])
print(tup2[::-1])

(3, 5, 6)
('Nokia', 'Apple', 'Vivo')


In [29]:
tuplist = list(tup1)
tuplist.append(10)
print(type(tuplist))
tup1 = tuple(tuplist)
print(tup1)
print(type(tup1))

<class 'list'>
(3, 5, 6, 2, 10, 10)
<class 'tuple'>


In [30]:
tup4 = (12,45,12,23,[6,2,8,14])
print(tup4)

(12, 45, 12, 23, [6, 2, 8, 14])


In [32]:
tuplist1 = list(tup4)
tuplist1.remove(12)
tup4 = tuple(tuplist1)
print(tup4)

(45, 12, 23, [6, 2, 8, 14])


In [1]:
#25 Jan
#Set
myset1 = {"dinesh","chennai",43,12}
print(myset1)
print(type(myset1))

{'chennai', 43, 12, 'dinesh'}
<class 'set'>


In [2]:
myset2 = set(("Tnagar","Nandanam","Adyar"))
print(myset2)
print(type(myset2))

{'Adyar', 'Tnagar', 'Nandanam'}
<class 'set'>


In [7]:
myset3 = {}
print(type(myset3))
myset3 = set()
print(type(myset3))

<class 'dict'>
<class 'set'>


In [5]:
for x in myset2: #access
    print(x)

Adyar
Tnagar
Nandanam


In [9]:
print(len(myset1))
print(len(myset2))
print(len(myset3))

4
3
0


In [10]:
#add #update
myset1.add("B.E")
print(myset1)
myset1.update(["MBA","PGDM","SEPO"])
print(myset1)

{'B.E', 'chennai', 43, 12, 'dinesh'}
{'B.E', 'SEPO', 'chennai', 43, 12, 'MBA', 'PGDM', 'dinesh'}


In [11]:
myset1.remove(43)
myset1.discard(100)
myset1.pop()

'B.E'

In [12]:
print(myset1)

{'SEPO', 'chennai', 12, 'MBA', 'PGDM', 'dinesh'}


In [13]:
myset2.clear()
del myset2

In [14]:
print(myset2)

NameError: NameError: name 'myset2' is not defined

In [16]:
set1 = {"Python","Java","c++","VB"}
set2 = {"Cobol","C#","Adobe","Python"}
unionset = set1 | set2 #union
print(unionset)
unionset1 = set1.union(set2)
print(unionset1)

{'Java', 'Adobe', 'c++', 'VB', 'C#', 'Cobol', 'Python'}
{'Java', 'Adobe', 'c++', 'VB', 'C#', 'Cobol', 'Python'}


In [18]:
interesect1 = set1 & set2 #intersection
print(interesect1)
interesect2 = set1.intersection(set2)
print(interesect2)

{'Python'}
{'Python'}


In [20]:
print(set1 - set2) #difference
print(set2 - set1)

{'Java', 'VB', 'c++'}
{'Adobe', 'C#', 'Cobol'}


In [21]:
#Dictionaries
dict1 = {"1":"Chennai","2":"Kochin","3":"Bangalore"}
print(type(dict1))

<class 'dict'>


In [23]:
dict2 = dict({"one":"Kolkata","two":"Mumbai","three":"Delhi"})
print(type(dict2))

<class 'dict'>


In [24]:
dict3 = {"name":"Dinesh","address":[10,40,'chennai']}
print(type(dict3))

<class 'dict'>


In [25]:
print(dict1["1"])
print(dict2["two"])
print(dict3["address"])

Chennai
Mumbai
[10, 40, 'chennai']


In [27]:
dict1["3"] = "Punjab"
dict2.update({"three":"Agra"})
print(dict1)
print(dict2)

{'1': 'Chennai', '2': 'Kochin', '3': 'Punjab'}
{'one': 'Kolkata', 'two': 'Mumbai', 'three': 'Agra'}


In [28]:
dict1.popitem()
print(dict1)

{'1': 'Chennai', '2': 'Kochin'}


In [29]:
dict2.pop("two")
print(dict2)

{'one': 'Kolkata', 'three': 'Agra'}


In [30]:
dict3.clear()
print(dict3)

{}


In [31]:
del dict3
print(dict3)

NameError: NameError: name 'dict3' is not defined

In [3]:
#26 Jan
#control structures - condition and loop
x = 1
if x>2:
    print("x is greater")
else:
    print("It is lesser")

It is lesser


In [9]:
#chain if
def fita(course):
    if course == "Python":
        print("Enrolled")
    elif course == "Java":
        print("Delayed")
    elif course == "C++":
        print("Valued")
    else:
        print("wrong choice")

fita("nkjn")

wrong choice


In [10]:
#nested if
n1 = 5
n2 = 10
if n2>=n1:
    if n1 == n2:
        print("Both are equal")
    else:
        print("not equal")
else:
    print(n1,"is greater")

not equal


In [11]:
#for, while
for x in range(1,11):
    print(x)

1
2
3
4
5
6
7
8
9
10


In [19]:
for x in range(10):
    if x>5:
        print("finished")
        continue
    print(x)

0
1
2
3
4
5
finished
finished
finished
finished


In [22]:
n = 5
for i in range(1,n+1,1):
    for j in range(1,i+1):
        print(j, end=" ")
    print(" ")

1  
1 2  
1 2 3  
1 2 3 4  
1 2 3 4 5  


In [23]:
for i in range(1,n+1,1):
    for j in range(1,i+1):
        print("*", end=" ")
    print(" ")

*  
* *  
* * *  
* * * *  
* * * * *  


In [25]:
n = 5
m = 5
for i in range(0,n+1):
    for j in range(m-i,0,-1):
        print(j,end =" ")
    print()

5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 



In [3]:
#27 Jan
#functions
def Fita():
    print("Welcome to FITA Acadey")

Fita()

Welcome to FITA Acadey


In [4]:
def Courses(name,duration):
    print("Course is",name)
    print("Duration is",duration)
Courses('Python','2 Months')

Course is Python
Duration is 2 Months


In [5]:
def addition(a,b):
    add = a+b
    return add
addition(4,8)

12

In [6]:
from random import randint
print(randint(6,10))

8


In [9]:
def calcluator(a,b):
    add = a+b
    sub=a-b
    mul=a*b
    div=a/b
    return add,sub,mul,div
q,w,e,r = calcluator(3,4)
print(q)
print(w)
print(e)
print(r)

7
-1
12
0.75


In [14]:
def employee(name,salary="25000"):
    print(name,salary)
employee("Jeeva")
employee("babu",30000)

Jeeva 25000
babu 30000


In [22]:
def add(num):
    if num:
        return num + add(num -1)
    else:
        return 0
add(4)

10

In [23]:
print(list(range(1,26,2)))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25]


In [24]:
x = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25]
print(max(x))

25


In [1]:
#30 Jan
#Numpy
import numpy as np

In [3]:
x = np.array([3,5,7,1,4]) #1D
print(x)
print(x.dtype)
print(x.shape)

[3 5 7 1 4]
int64
(5,)


In [7]:
x1 = np.arange(8)
print(x1)
x2 = np.arange(2,6)
print(x2)
x3 = np.arange(0,10,3)
print(x3)

[0 1 2 3 4 5 6 7]
[2 3 4 5]
[0 3 6 9]


In [8]:
mon = [[1,2,3],[4,5,6]]
d2 = np.array(mon) #2d
print(d2)
print(d2.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [9]:
mat_zeros = np.zeros(shape=(3,5))
print(mat_zeros)
mat_ones = np.ones(shape=(2,3))
print(mat_ones)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
ran_mat1 = np.random.random(size=(3,4))
print(ran_mat1)

[[0.20487376 0.76870225 0.16187288 0.28374579]
 [0.4539293  0.17712232 0.56038501 0.25242213]
 [0.47195963 0.36422082 0.82850366 0.90976455]]


In [13]:
ran_mat2 = np.random.randint(low = 0, high = 2, size=(3,4))
print(ran_mat2)

[[1 1 0 1]
 [1 0 1 0]
 [0 0 0 1]]


In [14]:
fita = np.arange(10)
print(fita)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
f1 = np.arange(0,20,3)
print(f1)
f2 = f1[::2]
print(f2)

[ 0  3  6  9 12 15 18]
[ 0  6 12 18]


In [20]:
matrix1 = np.random.randint(0,6,(3,5))
print(matrix1)
subm = matrix1[0:2, -2:]
print(subm)
subm1 = matrix1[:,3:1:-1]
print(subm1)

[[0 5 4 1 0]
 [0 3 1 0 1]
 [3 4 3 2 4]]
[[1 0]
 [0 1]]
[[1 4]
 [0 1]
 [2 3]]


In [24]:
spl = np.random.randint(0,6,(3,7))
sp1, sp2, sp3 = np.hsplit(spl,[4,6])
print(spl)
print(sp1.shape,sp1)
print(sp2.shape,sp2)
print(sp3.shape,sp3)

[[4 1 4 2 2 5 0]
 [0 2 3 2 2 3 3]
 [4 4 1 2 0 4 0]]
(3, 4) [[4 1 4 2]
 [0 2 3 2]
 [4 4 1 2]]
(3, 2) [[2 5]
 [2 3]
 [0 4]]
(3, 1) [[0]
 [3]
 [0]]


In [25]:
sp4, sp5 = np.vsplit(spl,[1])
print(sp4.shape,sp4)
print(sp5.shape,sp5)

(1, 7) [[4 1 4 2 2 5 0]]
(2, 7) [[0 2 3 2 2 3 3]
 [4 4 1 2 0 4 0]]


In [2]:
#01 feb
week = np.array([1,2,5,8,4,23,645,12,67])
week

array([ 1, 2, 5, 8, 4, 23, 645, 12, 67])

In [3]:
np.split(week,[3,5])

[array([1, 2, 5]), array([8, 4]), array([ 23, 645,  12,  67])]

In [4]:
tdarr = np.arange(28).reshape(7,4)
tdarr

array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23],
 [24, 25, 26, 27]])

In [6]:
v1,v2,v3 = np.vsplit(tdarr,[2,5])
v1

array([[0, 1, 2, 3],
 [4, 5, 6, 7]])

In [7]:
v2

array([[ 8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]])

In [8]:
v3

array([[20, 21, 22, 23],
 [24, 25, 26, 27]])

In [9]:
h1, h2 = np.hsplit(tdarr,[2])
h1

array([[ 0, 1],
 [ 4, 5],
 [ 8, 9],
 [12, 13],
 [16, 17],
 [20, 21],
 [24, 25]])

In [10]:
h2

array([[ 2, 3],
 [ 6, 7],
 [10, 11],
 [14, 15],
 [18, 19],
 [22, 23],
 [26, 27]])

In [11]:
sor = np.array([26,2,53,67,11,5,89])
sor

array([26, 2, 53, 67, 11, 5, 89])

In [13]:
sor1 = np.sort(sor)
sor1

array([ 2, 5, 11, 26, 53, 67, 89])

In [14]:
-np.sort(-sor)

array([89, 67, 53, 26, 11, 5, 2])

In [17]:
import random
stat = np.random.uniform(10,2,(3,3))
stat

array([[8.57001312, 4.24949152, 4.82985416],
 [6.83649784, 7.23310021, 3.32744449],
 [2.51864423, 7.05991457, 4.37252518]])

In [18]:
np.sort(stat,axis = 1)

array([[4.24949152, 4.82985416, 8.57001312],
 [3.32744449, 6.83649784, 7.23310021],
 [2.51864423, 4.37252518, 7.05991457]])

In [19]:
np.sort(stat,axis = 0)

array([[2.51864423, 4.24949152, 3.32744449],
 [6.83649784, 7.05991457, 4.37252518],
 [8.57001312, 7.23310021, 4.82985416]])

In [24]:
strarr = np.array(["Python","Java","Julia","VB"])
strarr

array(['Python', 'Java', 'Julia', 'VB'], dtype='%lt;U6')

In [26]:
strarr.sort()
strarr

array(['Java', 'Julia', 'Python', 'VB'], dtype='%lt;U6')

In [27]:
tdarr

array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23],
 [24, 25, 26, 27]])

In [29]:
tdarr.shape

(7, 4)

In [30]:
tdarr.ndim

2

In [31]:
addarr = np.array([3,8,1,2])
addarr

array([3, 8, 1, 2])

In [32]:
tdarr + addarr

array([[ 3, 9, 3, 5],
 [ 7, 13, 7, 9],
 [11, 17, 11, 13],
 [15, 21, 15, 17],
 [19, 25, 19, 21],
 [23, 29, 23, 25],
 [27, 33, 27, 29]])

In [33]:
addarr - 5

array([-2, 3, -4, -3])

In [34]:
addarr * 4

array([12, 32, 4, 8])

In [35]:
np.add(tdarr,5)

array([[ 5, 6, 7, 8],
 [ 9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20],
 [21, 22, 23, 24],
 [25, 26, 27, 28],
 [29, 30, 31, 32]])

In [36]:
np.subtract(tdarr,2)

array([[-2, -1, 0, 1],
 [ 2, 3, 4, 5],
 [ 6, 7, 8, 9],
 [10, 11, 12, 13],
 [14, 15, 16, 17],
 [18, 19, 20, 21],
 [22, 23, 24, 25]])

In [37]:
np.power(tdarr,2)

array([[ 0, 1, 4, 9],
 [ 16, 25, 36, 49],
 [ 64, 81, 100, 121],
 [144, 169, 196, 225],
 [256, 289, 324, 361],
 [400, 441, 484, 529],
 [576, 625, 676, 729]])

In [38]:
np.mean(tdarr)

13.5

In [39]:
np.sum(tdarr)

378

In [40]:
np.min(tdarr)

0

In [41]:
np.max(tdarr)

27

In [42]:
np.var(tdarr)

65.25

In [43]:
np.std(tdarr)

8.077747210701755

In [44]:
np.log(tdarr)

<ipython-input-44-cf7e73bf480e>:1: RuntimeWarning: divide by zero encountered in log
  np.log(tdarr)


array([[ -inf, 0. , 0.69314718, 1.09861229],
 [1.38629436, 1.60943791, 1.79175947, 1.94591015],
 [2.07944154, 2.19722458, 2.30258509, 2.39789527],
 [2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
 [2.77258872, 2.83321334, 2.89037176, 2.94443898],
 [2.99573227, 3.04452244, 3.09104245, 3.13549422],
 [3.17805383, 3.21887582, 3.25809654, 3.29583687]])

In [45]:
np.log10(tdarr)

<ipython-input-45-4f6c34faf5ef>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(tdarr)


array([[ -inf, 0. , 0.30103 , 0.47712125],
 [0.60205999, 0.69897 , 0.77815125, 0.84509804],
 [0.90308999, 0.95424251, 1. , 1.04139269],
 [1.07918125, 1.11394335, 1.14612804, 1.17609126],
 [1.20411998, 1.23044892, 1.25527251, 1.2787536 ],
 [1.30103 , 1.32221929, 1.34242268, 1.36172784],
 [1.38021124, 1.39794001, 1.41497335, 1.43136376]])

In [46]:
#Pandas
import pandas as pd

In [47]:
s = pd.Series([10,20,30,40,50])
type(s)

pandas.core.series.Series

In [48]:
s.axes

[RangeIndex(start=0, stop=5, step=1)]

In [49]:
s.dtype

dtype('int64')

In [51]:
s.size

5

In [52]:
s.ndim

1

In [53]:
s.values

array([10, 20, 30, 40, 50])

In [54]:
s.head(2)

0 10
1 20
dtype: int64

In [56]:
s.tail(3)

2 30
3 40
4 50
dtype: int64

In [57]:
s[2]

30

In [58]:
pd.Series([13,214,210,440,53])

0 13
1 214
2 210
3 440
4 53
dtype: int64

In [60]:
pd.Series([13,210,214,53,440],index=[4,1,0,3,2])

4 13
1 210
0 214
3 53
2 440
dtype: int64

In [61]:
ages = {"suresh":23,"babu":34,"Sam":19}
ages

{'suresh': 23, 'babu': 34, 'Sam': 19}

In [62]:
pd.Series(ages)

suresh 23
babu 34
Sam 19
dtype: int64

In [66]:
a = np.array([23,"Python","java",12,76])
a

array(['23', 'Python', 'java', '12', '76'], dtype='%lt;U21')

In [67]:
pd.Series(a)

0 23
1 Python
2 java
3 12
4 76
dtype: object