In [2]:
#Numpy
import numpy as np
np.array(34)

array(34)

In [2]:
np.array([3,5,7,23])

array([ 3, 5, 7, 23])

In [6]:
np.array([[5,6,1,2],[2,3,5,8]])

array([[5, 6, 1, 2],
 [2, 3, 5, 8]])

In [11]:
x = np.array([4,6,8,2])
x.ndim
x.shape
x.size
x.dtype
type(x)

numpy.ndarray

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.full((2,4),3)

array([[3, 3, 3, 3],
 [3, 3, 3, 3]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
 [0., 1., 0.],
 [0., 0., 1.]])

In [17]:
np.arange(1,20,2)

array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19])

In [18]:
np.linspace(0,1,10)

array([0. , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
 0.55555556, 0.66666667, 0.77777778, 0.88888889, 1. ])

In [21]:
np.random.randint(2,10,9)

array([9, 4, 4, 4, 2, 6, 9, 6, 6])

In [22]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a[1]
a[5::]
a[3:7]
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12]])

In [32]:
arr[0]
arr[1,2]
arr[2][2::]

array([11, 12])

In [33]:
arr1 = np.array([[3,4,5,2],[2,3,4,7],[9,8,1,4]])
arr1

array([[3, 4, 5, 2],
 [2, 3, 4, 7],
 [9, 8, 1, 4]])

In [34]:
arr>2

array([[False, False, True, True],
 [ True, True, True, True],
 [ True, True, True, True]])

In [35]:
arr>arr1

array([[False, False, False, True],
 [ True, True, True, True],
 [False, True, True, True]])

In [36]:
arr1[arr>2]

array([5, 2, 2, 3, 4, 7, 9, 8, 1, 4])

In [3]:
ab = np.random.randint(20, size=(4,5))
ab

array([[ 4, 5, 2, 10, 4],
 [ 8, 7, 4, 19, 8],
 [ 6, 13, 12, 10, 13],
 [ 9, 4, 17, 5, 12]])

In [4]:
sub_ab = ab[:2,:3]
sub_ab

array([[4, 5, 2],
 [8, 7, 4]])

In [5]:
sub_ab[0,0] = 55
sub_ab

array([[55, 5, 2],
 [ 8, 7, 4]])

In [6]:
ab

array([[55, 5, 2, 10, 4],
 [ 8, 7, 4, 19, 8],
 [ 6, 13, 12, 10, 13],
 [ 9, 4, 17, 5, 12]])

In [8]:
n = np.arange(1,10)
n
n.shape

(9,)

In [9]:
n_shape = n.reshape(3,3)
n_shape

array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [13]:
ab.reshape(-1)
ab
ab.flatten()

array([55, 5, 2, 10, 4, 8, 7, 4, 19, 8, 6, 13, 12, 10, 13, 9, 4,
 17, 5, 12])